# Data Preparation

### Import Libraries


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv
import random

### 1. Load Data

##### 1.1 From .csv

In [3]:
# data = pd.read_csv('CarPrice_Assignment.csv',delimiter = ',')

# print(data)
# headers = data[0,:]
# print(headers)
# data = data[1:,:]
# print(data[:5,:])

##### 1.2 From sklearn datasets

In [4]:
from sklearn.datasets import load_boston

##### 1.3 From .txt

In [5]:
# data = np.genfromtxt('Housing_data.txt',delimiter = ',', dtype=str);
'''
data is imported as numpy array, do not forget to remove the header
'''
# data

'\ndata is imported as numpy array, do not forget to remove the header\n'

### 2. Extract X and y

##### 2.1 Pandas

In [6]:
# extract x
# col = ['enginesize','horsepower','peakrpm']
# X = data[col]
# print(X.iloc[:5,:])

# # extract y
# y = data['price'] 
# print(y.iloc[:5])

##### 2.2 Sklearn Datasets (Bunch)

In [7]:
boston = load_boston()
X = boston.data
y = boston.target
# print(X)

##### 2.3 Numpy

In [8]:
# Extract headers and data
# headers = raw_data[0,:];
# print(headers)
# data = np.array(raw_data[1:,:], dtype=float);
# print(data)

In [9]:
# # see headers
# headers = data[0,:]
# print(headers)

### 3. Shape Checking

In [10]:
# check number of samples
m = X.shape[0]
print("Number of samples: ", m)
# check number of features
n = X.shape[1]
print("Number of features: ", n)

# check number of y
assert m == y.shape[0]

Number of samples:  506
Number of features:  13


### 4. Cleaning data

##### 4.1 Check for missing data

In [11]:
#Pandas 
#Convert to DataFrame to check for missing data
df = pd.DataFrame(X)
print('Missing values for train data:\n------------------------\n', df.isnull().sum())

Missing values for train data:
------------------------
 0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64


##### 4.2 Handling Missing Values

###### 4.2.1 Discrete

##### Yes and No

In [12]:
# print(data_train['Married'].value_counts())

# married = data_train['Married'].value_counts()
# print('Elements in Married variable', married.shape)
# print('Married ratio ', married[0]/sum(married.values))

# def fill_martial_status(data, yes_num_train, no_num_train):        
#     data['Married'].fillna('Yes', inplace = True, limit = yes_num_train)
#     data['Married'].fillna('No', inplace = True, limit = no_num_train)  

# fill_martial_status(data_train, 2, 1)
# print(data_train['Married'].value_counts()) 
# print('Missing values for train data:\n------------------------\n', data_train.isnull().sum())

##### Numeric

In [13]:
# print(data_train['Dependents'].value_counts())
# dependent = data_train['Dependents'].value_counts()

# print('Dependent ratio 1 ', dependent['0'] / sum(dependent.values))
# print('Dependent ratio 2 ', dependent['1'] / sum(dependent.values))
# print('Dependent ratio 3 ', dependent['2'] / sum(dependent.values))
# print('Dependent ratio 3+ ', dependent['3+'] / sum(dependent.values))

# def fill_dependent_status(num_0_train, num_1_train, num_2_train, num_3_train, num_0_test, num_1_test, num_2_test, num_3_test):        
#     data_train['Dependents'].fillna('0', inplace=True, limit = num_0_train)
#     data_train['Dependents'].fillna('1', inplace=True, limit = num_1_train)
#     data_train['Dependents'].fillna('2', inplace=True, limit = num_2_train)
#     data_train['Dependents'].fillna('3+', inplace=True, limit = num_3_train)
#     data_test['Dependents'].fillna('0', inplace=True, limit = num_0_test)
#     data_test['Dependents'].fillna('1', inplace=True, limit = num_1_test)
#     data_test['Dependents'].fillna('2', inplace=True, limit = num_2_test)
#     data_test['Dependents'].fillna('3+', inplace=True, limit = num_3_test)

# fill_dependent_status(9, 2, 2, 2, 5, 2, 2, 1)

# print(data_train['Dependents'].value_counts())

# # Convert category value "3+" to "4"

# data_train['Dependents'].replace('3+', 4, inplace = True)
# data_test['Dependents'].replace('3+', 4, inplace = True)

##### 4.2.2 Continuous (filled with mean)

In [14]:
# print(data_train['LoanAmount'].value_counts())

# LoanAmt = data_train['LoanAmount'].value_counts()

# print('mean loan amount ', np.mean(data_train["LoanAmount"]))

# loan_amount_mean = np.mean(data_train["LoanAmount"])

# data_train['LoanAmount'].fillna(loan_amount_mean, inplace=True, limit = 22)
# data_test['LoanAmount'].fillna(loan_amount_mean, inplace=True, limit = 5)
# data_train.isnull().sum()
# # data_test.isnull().sum()

#### Double Check

In [15]:
print(df.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64


#### String to number conversion

In [16]:
# def convert_vals(col,col_name,answer1, answer2 ,answer3):
#     ixd_1 = np.where(data_train[col_name] == answer1)
#     ixd_0 = np.where(data_train[col_name]== answer2)
#     ixd_2 = np.where(data_train[col_name]== answer3)
#     for i in ixd_1:
#         data_train.iloc[i,col] = 1
#     for i in ixd_0:
#         data_train.iloc[i,col] = 0
#     for i in ixd_2:
#         data_train.iloc[i,col] = 2

# convert_vals(1,'Gender','Male','Female','')
# convert_vals(2,'Married','Yes','No','')
# convert_vals(4,'Education','Graduate','Not Graduate','')
# convert_vals(5,'Self_Employed','No','Yes','')
# convert_vals(11,'Property_Area','Semiurban','Rural','Urban')
# convert_vals(12,'Loan_Status','Y','N','')

# cols = ['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area']

# X = data_train[cols]
# X = X.astype(float)
# X = np.array(X)
# # print(X)

# Y = data_train['Loan_Status']
# Y = Y.astype(float)
# Y = np.array(Y)

##### Delete everything that's missing

In [17]:
# df["Text"] = df['Title'].fillna('') + ' ' + df['Review Text'].fillna('')
# df = df[df['Text'] != ' ']

##### Replacing fancy stuff

In [18]:
# df['Text'] = df['Text'].str.replace('[^a-zA-Z0-9 \n\.]|\.', '')
# df['Text'] = df['Text'].str.lower()
# df = df[['Text', 'Rating']]

#### Convert back to numpy

In [19]:
X = df.values
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


#### Plot

In [20]:
# plt.scatter(X[:,1], y)
# plt.xlabel('x-axis')
# plt.ylabel('y-axis')
# plt.title('plot')
# plt.show()

### 5. Final prep

##### 5.1 Feature engineering

In [21]:
# No dummy
def x_polynomial(x, d):
    for i in range(1,d):
        a = np.concatenate((x,x**(i+1)), axis = 1)
    return a
X = x_polynomial(X,3)
print(X)
print(X.shape)

[[6.32000000e-03 1.80000000e+01 2.31000000e+00 ... 3.58157700e+03
  6.25235022e+07 1.23505992e+02]
 [2.73100000e-02 0.00000000e+00 7.07000000e+00 ... 5.63975200e+03
  6.25235022e+07 7.63551944e+02]
 [2.72900000e-02 0.00000000e+00 7.07000000e+00 ... 5.63975200e+03
  6.06197221e+07 6.54508270e+01]
 ...
 [6.07600000e-02 0.00000000e+00 1.19300000e+01 ... 9.26100000e+03
  6.25235022e+07 1.79406144e+02]
 [1.09590000e-01 0.00000000e+00 1.19300000e+01 ... 9.26100000e+03
  6.09072020e+07 2.72097792e+02]
 [4.74100000e-02 0.00000000e+00 1.19300000e+01 ... 9.26100000e+03
  6.25235022e+07 4.89303872e+02]]
(506, 26)


##### 5.2 Normalization/Standardization

###### 5.2.1 Sklearn

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)
print(X.shape)
# print(X)

(506, 26)


##### 5.2.2 Scratch

In [23]:
# X = (X-np.mean(X, axis = 0))/np.std(X, axis = 0)
# print(X)

### 6. Spliting train and test

##### 6.1 Sklearn

In [24]:
# from sklearn.model_selection import train_test_split

# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

# # double check the shapes
# assert X_train.shape[0] == y_train.shape[0]
# # assert len(X_train)  == len(y_train)
# assert X_test.shape[0] == y_test.shape[0]
# # assert len(X_test) == len(y_test)

# print('shapes of X_train, y_train')
# print(X_train.shape,y_train.shape)
# print('shapes of X_test, y_test')
# print(X_test.shape,y_test.shape)

##### 6.2 Scratch

In [25]:
# Random index 
import random
m = X.shape[0]
idx = np.arange(0,m)
random.shuffle(idx)

# Numpy
X = X[idx,:]

# Pandas
# X = X.iloc[idx,:]

# X = X.reset_index()
# X.shape

In [26]:
import random
m, n = X.shape
idx = np.arange(0, m)
random.shuffle(idx)
percent_train = .7
m_train = int(m * percent_train)
train_idx = idx[0:m_train]
test_idx = idx[m_train:]
X_train = X[train_idx,:];
X_test = X[test_idx,:];

y_train = y[train_idx];
y_test = y[test_idx];

# double check the shapes
assert X_train.shape[0] == y_train.shape[0]
# assert len(X_train)  == len(y_train)
assert X_test.shape[0] == y_test.shape[0]
# assert len(X_test) == len(y_test)

print('shapes of X_train, y_train')
print(X_train.shape,y_train.shape)
print('shapes of X_test, y_test')
print(X_test.shape,y_test.shape)

shapes of X_train, y_train
(354, 26) (354,)
shapes of X_test, y_test
(152, 26) (152,)


#### Addition of dummy

In [47]:
# add dummy at X_train
intercept = np.ones((X_train.shape[0], 1))
X_train = np.concatenate((intercept, X_train), axis=1)

# add dummy at X_test
intercept = np.ones((X_test.shape[0], 1))
X_test = np.concatenate((intercept, X_test), axis=1)

print('shapes of X_train, y_train with DUMMY added')
print(X_train.shape,y_train.shape)
print('shapes of X_test, y_test with DUMMY added')
print(X_test.shape,y_test.shape)

shapes of X_train, y_train with DUMMY added
(354, 28) (354,)
shapes of X_test, y_test with DUMMY added
(152, 28) (152,)
